sudo: required
dist: xenial
before_install:
  - sudo snap install lxd
  - ls -la /snap/bin
  - lxc version
  - /snap/bin/lxc version
  - sudo lxd init --auto
  - sudo lxc network create lxdbr0 ipv6.address=none ipv4.address=10.0.3.1/24 ipv4.nat=true
  - sudo lxc network attach-profile lxdbr0 default eth0
  - sudo chmod 777 /var/lib/lxd/unix.socket
  - ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -P ""

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  allow_failures:
    - python: "3.7-dev"

# We set HOME because lxc needs somewhere writable to not crash during testing.
script:
  - cp -R /home/travis/.ssh $TRAVIS_BUILD_DIR
  - HOME=$TRAVIS_BUILD_DIR make travis

after_success:
  - codecov
branches:
  only:
    - master
