sudo: required
dist: trusty
env:
  - PATH=/snap/bin:$PATH

before_install:
  - make travis-sysdeps
  - ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -P ""

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  allow_failures:
    - python: "3.7-dev"

# We set HOME because lxc needs somewhere writable to not crash during testing.
script:
  - cp -R /home/travis/.ssh $TRAVIS_BUILD_DIR
  - HOME=$TRAVIS_BUILD_DIR make travis

after_success:
  - codecov
branches:
  only:
    - master
